### ISSUE TITLE
Windows locks on folders in web root after starting server

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#101]
In a recent update of Runwar, there are now file/folder locks on stuff in the webroot that prevents people from interacting with their files after starting a server.  A common example is trying to `npm install` something.  There will be folder locks on the `node_modules` folder and the stuff inside of it even though the CF server isn't touching those folders.  I've traced the file handles to the java process with Sysinternals Process Explorer, but I don't know of a good way to trace the open files inside the JVM to see where they're coming from.  The file locks are there on both Adobe and Lucee servers, so it appears to be at the Runwar/Undertow level.

**Comment by davemerrill** [comment]
Seeing the same thing, with at least some directories and files. I have apps that need to delete both types of items, and an Ant build for one app, both fail quite frequently. For the ant build, I can stop the server, but that's obviously not a solution for the app.

It's definitely not ALL files or dirs, as one app constantly creates and deletes its own files successfully. Not sure what the pattern is, but it is truly annoying.

It's also a factor in me not pushing CommandBox (yet) as a general dev environment at work., where it's a great fit in most respects.

**Comment by denuno** [comment]
What's the best way to reproduce this?  And which versions of Windows are we talking about?  (I assume it's only Windows since it's got weird locking issues.)

**Comment by bdw429s** [comment]
@denuno I've gotten reports for several versions of Windows, but I can reproduce it very easily with the node_modules example on Windows 7 on both Lucee and Adobe CF.  I haven't verified this, but someone on Slack claimed they tested several versions of CommandBox and it started with CommandBox 3.7.  
That version of CommandBox switched from Runway `3.6.0-SNAPSHOT` to `3.6.1-SNAPSHOT` but I'd take those exact versions with a grain of salt.

**Comment by davemerrill** [comment]
I've seen it a lot with both Windows 7 and 10. My actual circumstances
aren't easily encapsulated for testing, but briefly:

- I have an app that's delivered as a single-file cfm installer. The
installer contains an encoded zip of the actual app, plus UI and code to
decode it, write it as a zip file on disk, then extract it and delete the
zip. The extraction may be overwriting a previous install, and and
sometimes it can't do at least some of those files, but it nearly always is
unable to delete the zip it extracted.

- That same app has an Ant build process that generates the installer from
the app source files. The build starts by deleting the 'dist' directory
(rather than all the stuff in it individually), and that pretty much always
fails if it's located under a running CommandBox server. Not sure if it
only happens when some of the files in that directory have been accessed,
or always, since I'm typically running a build after making changes to the
live source.

Thanks for looking into this Denny. As I've said, it's not only that my
specific workflows get hung up, it's that any differences between the
standalone servers and the same engine versions under CommandBox, make me
reluctant to recommend it to my company for dev environments. I'm using it
myself, and it's a wonderfully convenient way to stand up any flavor of
server anywhere, but I'm aware of the differences.and workarounds. I'd
rather not have to bring a list of caveats.

**Comment by bdw429s** [comment]
@denuno Where you able to reproduce this one?

**Comment by davemerrill** [comment]
Hit this again today, source control couldn't update all files in the app
until I stopped the server.

Would be handy to get to the bottom of it.

**Comment by denuno** [comment]
Any chance one of you could provide a recipe?  I cannot reproduce the lock, but there are so many ways to skin cats I'm not sure I'm doing the same one.  I tried with a npm project, but I use Gradle for npm stuff, so maybe that has some effect, as I didn't have any trouble rebuilding directories and files and whatnot while the server was running... Like, does this occur within the CommandBox CLI alone, or does it happen from the normal commandline/external tools too?  Is there maybe a project I could check out from somewhere that would be a good occurrence generator?

**Comment by djcard** [comment]
Just to echo, I've seen this with Windows 10 and CommandBox 3.9.2+00826. I have a number of students who have run into it as well. I don't have an exact steps to reproduce since it usually starts off with thinking its another issue and then circling around to it being the locking problem.

**Comment by denuno** [comment]
Perhaps the next release will have some impact on this.  It's in develop right now, but it contains the latest version of Undertow, plus some other library updates that may or may not have some effect.  I haven't tried much more testing myself, if there's even a simple recipe that works 1 of 5 tries that'd help. :smiley:

**Comment by bdw429s** [comment]
Gavin was going to post some details to reproduce on this as well.  He was telling me today it's super easy and he hits it all the time.

**Comment by gpickin** [comment]
Here is a simple repro.
I figured out that you cannot delete folders which have folders with children.

Its uploading to youtube right no.

**Comment by bdw429s** [comment]
Thanks Gavin.  Hopefully this will help @denuno nail this down once and for all.

**Comment by denuno** [comment]
It's already helpful-- that's weird!  I was assuming it had to do with files that were served at least once. That it's locking with just creating/deleting folders with children is mega-odd.

My experiments revolved around firing up runwar, pulling down some node deps, browsing some files, and then deleting the directories-- and they worked every time, (other than windows being unable to delete a folder with a long name) even with folders containing many many children (gotta love NPM dependency management ;) ) so it's weird that I didn't run into it...

I was probably using one that I'd built locally though, and that's been updated to a more recent version of undertow for a while, there's a slim chance that's why I didn't see it.  Regardless, I'll give this scenario a spin and see what I can see-- thanks a bunch @gpickin !

**Comment by djcard** [comment]
I’ll back up that that is part of it. I have no idea the steps involved that cause it but I have noticed that I’ve had to shut down servers to delete folders at times. I think files and empty folders delete but not ones with anything in them.

**Comment by denuno** [comment]
Found what was going on.

You can add resource change listener support (like for WEB-INF/web.xml or whatnot I imagine), and then add listeners-- I'd enabled support but not added any listeners, thinking it wouldn't do anything without a listener, and thinking wrong, heh!  We can still enable it at some point, I sorta-kinda added an option for it, just set to `false` for now.

If this seems to fix it, and there aren't any other show-stoppers, I'll cut a release.

**Comment by davemerrill** [comment]
That's great news Den, thank you. I gather you found a reproducible test
case?

**Comment by bdw429s** [comment]
I just bumped CommandBox's snapshot to include the new `3.8.0-SNAPSHOT` of runwar.  It will be built in a few minutes.  Please grab the latest CommandBox snapshot and see if this issue has cleared up!

**Comment by denuno** [comment]
Yep Dave, the video did the trick for reproducing, and theoretically fixing! :smiley:
