### ISSUE TITLE
Name of server out log has changed

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#109]
The `server.out.txt` log has changed to `server.log`.  There are people out there who have scripts dependant on the name of that log file.  Is there a setting where I can control the name to get the original name back?

**Comment by bdw429s** [comment]
Will we be able to revert this name?

**Comment by denuno** [comment]
Yep, this is configurable.  I went ahead and switched it back to `.txt`.  Since prefixes have changed too I thought 6 of one-- at least people would know something changed. :wink:

Like I've mentioned, we're using log4j now, so basically we can do what it can do (check that config file I linked to in slack for an example).

**Comment by bdw429s** [comment]
>  I went ahead and switched it back to .txt

Like just now?  I didn't see any commits just now but perhaps you just haven't pushed yet.

**Comment by bdw429s** [comment]
Oh, I see what happened.  You tried to change it back, but not quite.  The server log name is currently:

```bash
server..out.txt
```

Check out the extra period in there.

**Comment by bdw429s** [comment]
I think this is ok now.
