### ISSUE TITLE
Starting background server uses JVM args in two java processes.

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#21]
When working with the Fusion Reactor guys to get FR running CommandBox, they pointed out that the java agent for FR was getting loaded twice-- once on the temporary process that CommandBox spins up and again on the actual server process.  The temp process exits once the server is running, but causes conflicts since FR is trying to load twice at the same time on two processes.

When starting a background server, I need a way to specify JVM args to be passed along to the actual server process without actually having them apply to the intermediate process.

**Comment by denuno** [comment]
I think I got this going in the develop branch.  I added a new option named jvmargs, which accepts a semi-colon-separated list of JVM arguments.  
Ex: 
```
-jvmargs "-agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:39988;-Djava.library.path=/workspace/runwar/lib;-Dfile.encoding=UTF-8"
```
We'll have to think about this a little-- I chose semi-colon since I don't believe it's common to have one in a jvm arg, but we may need to use something else if I'm mistaken... I reckon if we can get it to work with FR that'll be a good first step, since I added it to try to address that issue.

**Note:  This is only applied when running as a background process right now**

**Comment by bdw429s** [comment]
Thanks.  If I have a JVM arg with a double quote in it, I assume I'd use the standard escaping rules?  For what it's worth, Fusion Reactor 6.2 released a fix that allowed it to work, but I'm sure there will be other issues related to this in the future so it's a good thing to get nailed down.

Can you clarify what the semi colon is for?  Is that to delimit each arg?  Does it really matter how many specific args there are, or can it simply be a string that's appended in?  Right now I allow CommandBox users to specify their own JVM args for a server, and it's just a string with whatever they want in it.

**Comment by denuno** [comment]
The underlying implementation expects a list, one entry for each argument+value, so we have to split it up somehow.

I was hoping to just use a string with a split() on spaces, but thought there might be spaces inside stuff we didn't want split, so opted for the semi-colon.

We could try using the space, or adding some parsing code, but as this is the first time this has come up, and seemed to be an issue on their end that they've since fixed, I'm not too keen on working on parsing the arguments out of a string myself... some of those JVM ones can be pretty gnarly, as you can see from my 'simple' example above.  I'm down to roll with splitting on a space instead of a semi-colon though, until we actually have a case where that won't work (and thus you could just pass in the string, theoretically, and not worry about delimiters).

**Comment by bdw429s** [comment]
Hmm, I see.  The trick is, I have no control right now over (parts of) the incoming string.  Users are allowed to pass their own collection of custom JVM arguments in a string and so far, I've just been slapping them onto the command that gets run.  I almost implemented it as an array, but had stuck with a string just to keep it simple since I didn't care how many JVM args they gave me.  

I don't think it's going to matter though... I just traced the ProcessBuilder code through, and the first thing it does is simply concatenate the array right back together so it will never know if the params came through as 
```
[
  'binary',
  '--arg1',
  '--arg2'
]
```
or 
```
[
  'binary',
  '--arg1 --arg2'
]
```
since it all ends up as `binary --arg1 --arg2` at the end of the day.
