### ISSUE TITLE
Pass right click tray options in ad-hoc JSON

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#22]
I've got a handful of pre-made JSON files that CommandBox uses depending on the engine being used.   It would be nice to make ad-hoc contributions without needing to write out a file. For instance, if the user enables my soon-to-be-written Fusion Reactor module, I'd like to toss in an extra menu item to open the FR web console.  I can toss the JSON in a temp file and point to it, but it would be cool to just be able to pass ad-hoc JSON into Runwar.  Heck, I could even allow users to add their own ad-hoc contributions via their server.json for quick links into their app.

**Comment by denuno** [comment]
We could do something like this, but keep in mind that there's a limit to how much you can pass on the command line without using a file to store the arguments (this is an OS limit), and I'm thinking JSON menu info would use that up pretty quick.

It's probably better to use a file and just write it on the fly before starting or some-such, versus adding this feature.

Another theoretical option would be to manage our own server process, instead of backgrounding it, and then we could just call the code that does the menu stuff from CFML, and configure things during runtime... but that might be much easier said than done. :-)

**Comment by bdw429s** [comment]
Good call on the arg limit.  I wasn't aware of that.  I'm fine with writing a temp file if it prevents us from hitting limits on the length of JVM args.  I would love to be able to handle this with CFML.  The only detriment I can think of to that is that there would be a small delay when the CLI started up to process their right click.  I love the idea of having completely dynamic right click menus that can point to a CFML function.  I already have it in the works to allow CommandBox module devs to register their own menu options via the `onServerStart` interception point.  

Question: if I write a temp JSON file, how long does it need to live for.  If it's put in a temp directory, it might get cleared out quickly.  Will Runwar read it right away and then cache its contents?

**Comment by bdw429s** [comment]
Question: if I write a temp JSON file, how long does it need to live for. If it's put in a temp directory, it might get cleared out quickly. Will Runwar read it right away and then cache its contents?

**Comment by bdw429s** [comment]
Resolved by writing temp files
https://ortussolutions.atlassian.net/browse/COMMANDBOX-428
