### ISSUE TITLE
file list still displays after adding index file.

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#23]
Steps to reproduce:

1. Start CommandBox server in empty folder (or a folder without an `index.cfm` at least)
2. Browser opens with file list showing
3. Create an `index.cfm` file
4. Refresh browser.  File list still displays even though the `index.cfm` should be run
5. This continues until server is restarted

**Comment by jay2001** [comment]
This will happen in sub directories as well. If you create an empty sub directory you get this issue, if you put the index.cfm in it before opening in the browser it works as expected.

**Comment by denuno** [comment]
I think I have this sorted for the next release, which will probably be Sunday evening.

**Comment by denuno** [comment]
Well, it turned out to be something a bit different than I thought, and rather tricky.

The resource type for the  path is cached in the ServletPathMatcher when it is run on the initial request for the resource, which is when the welcom-file list is checked.

What this amounts to is that the welcome file list is only checked for once.

There doesn't seem to be any easy way to disable the path cache, but it can be invalidated.  To test, I added a resource watcher that invalidates it whenever a file is added.  This works, and I like the idea of enabling, say, config-file watching, but that should be it's own feature-- it's a pretty heavy-weight solution just to get new welcome files picked up.

I'm open to ideas.  What I'm thinking now is to maybe add a check for a specific URL query parameter or something to invalidate the cached paths.  That's kinda weak, but perhaps better than taking the rather large hit resource monitoring must add.  Plus, there's no need to add another config option that way.

Otherwise, we'll need some kind of switch, and then choose a default behaviour, etc..

Hrm, I might just see about replacing the ServletPathMatcher with our own implementation, or simply invalidating the cache with each request... if I have to add an option, I'd probably just go with enabling resource watching, and probably tie the urlRewriteFilter in too, so you could edit the rewrites without restarting, etc..

**Comment by bdw429s** [comment]
Thanks for the update @denuno , I'm surprised Undertow hasn't had people run into this more often, but I suppose Java apps don't usually include JIT deployments like that.  Would it be possible to invalidate the cache for a URL if that URL displayed a file listing specifically?  I would suppose you would want to cache the resource provider for actual files that were resolved/served/etc, but browsing a directory of files seems like the outside edge case that's less likely to be part of a production app.

**Comment by denuno** [comment]
So what I ended up doing was checking to see if the path ends with "/" -- which all directories seem to do with Undertow -- and if it does, reset the cache.

I tied it to the directoryBrowing parameter too, so it'll only do that if you have directory browsing enabled.

I like this much better that the other approaches- though at some point we may want to enable resource monitoring, so I kept that code in there, commented out for now.
