### ISSUE TITLE
Ability to customize 404 page (and other relevant 40x/50x) statuses

### ISSUE THREAD

**Issue by bdw429s** [cfmlprojects/runwar#27]
If I hit a 404 through the default resource handler in Runwar, I just see the text "Not Found".  Allow the user to customize the html file to be loaded in the event of errors.

**Comment by denuno** [comment]
You can actually control this via web.xml, by setting error pages.

```
<error-page>
    <error-code>403</error-code>
    <location>/403.html</location>
</error-page>

<error-page>
    <location>/error.html</location>
</error-page>
```

However, that wasn't actually working until I added it to the web.xml parser, so, um, yeah, setting them that way should at least work in 3.4.9.

I kinda also like the fast method of passing them in, though in reality it's probably better (more portable) to use web.xml... so we could add, like:

 errorpages="400:/some/location,401:/some/location"

As an argument, allowing `errorpages="some/location"` (no code) to mean the default.

I'm not married to that argument name or format, but I'm warming to the idea, and think it'd be pretty handy.

**Comment by bdw429s** [comment]
@denuno Thx for letting me know about the `web.xml` settings.  For the most part, it's not easy for a CommandBox user to edit their `web.xml` on the fly since it's downloaded and deployed for them. (An `onServerStart()` interceptor would be the closest they could get)  I've also tried to avoid adding the full breadth of servlet settings to CommandBox, but I don't mind too much adding settings that they would normally put in Apache, IIS, or Nginx.  At the end of the day, I can have CommandBox edit their `web.xml` on the fly or I can pass the error pages to Runwar via an arg-- it will all be transparent to the users who will just add their settings to their CommandBox server config.  

Given the option, I'd probably prefer a dedicated arg just since manipulating the `web.xml` is a bit more of a pain.  Quick question-- is there even a `web.xml` for the "embedded" Lucee 4 server, or only in the standalone servers where I download a CF engine WAR for them.

**Comment by bdw429s** [comment]
Hey @denuno Glancing at the code, is this the correct format that you ended up implementing?
```
--error-pages="404=/path/to/404.html,500=/path/to/500.html,1=/path/to/default.html"
```
Also, can you help clarify in which scenarios the default is used?  Is that when there is no error page specified for the exact status code in question?  Do error pages have to be html? If I specify a .cfm error page, will it actually process via the CF engine?

**Comment by bdw429s** [comment]
@denuno Can you answer my questions above when you get a chance please?

**Comment by bdw429s** [comment]
I played around with this a bunch tonight to try and figure out what works.

**500** -  Not sure how to test?

**Default** -  Not sure how to test?

**404** - See below
- `/404.html` with leading slash and matching file in webroot works.
- `/404.cfm` Same as above, but with CFML code works-- nice touch!!
- `404.html` _without_ leading slash throws crazy Undertow exception: `java.lang.IllegalArgumentException: UT000068: Servlet path match failed`
- `C:\404.html` absolute path just returns empty page with no errors in logs

Is there any way we can make these be an absolute path so the files don't have to be in the webroot?  Also, if I provide a totally bogus path, it would be nice to at least have an exception in the logs or something instead of a white page of death.

And on the note of using a .cfm file for a 404, IIS will do this but it also passes the original missing path to the 404 template as a query string I believe so you can see where the user was going and handle it dynamically.  Can you do the same, or is this all handled by Undertow?

**Comment by denuno** [comment]
I'm not sure how you'd test a 500 either, I think it may only be useful for JSP?

The `default` is the catch-all, so any error will be forwarded to the location specified, unless there's a specific errorPage with the specific code defined, which will take precedence.

We can fix the crazy Undertow exception for a location with a missing leading slash easy enough, but I can't think of a way to use an absolute path, because all those error pages do is give a location to forward the request to (which is why CFML works, as would any valid location).  The responsibility is on the receiving end, which means that it's possible to use an absolute path, but you have to get it from somewhere else, basically.

So there are a couple ways to achieve absolute paths:

- Via adding a CFML mapping (although note that top level mappings have to exist for Adobe, but not for Lucee-- meaning a mapping of `/errors/` will only work on Adobe if there's an webroot/errors directory, whereas with Lucee the directory can be anywhere... I dunno if this changed with 2016, haven't tested in a while)
 
- Via a rewrite, which changes `/404.cfm` to somewhere more specific.  Note that you still basically have the same problem though, these are all just URLs, and have nothing to do with the filesystem, per se.
 
- Via a bit of magic in the ResourceMapper that looks for a special prefix.  The ResourceMapper is the thing that maps URLs to the filesystem, so it can do stuff like checking for file existence, etc..  (You'll note that it'll throw a warning if you pass in a 'virtual directory' mapping that doesn't exist.)  This would amount to the same thing as passing in a virtual dir of '/errors/' and then setting the errorPage URL to '/errors/404.cfm', which has the benefit of being explicit, over using some type of magic prefix. 

The CF mapping route has portability going for it-- you'd have to add virtual dirs/aliases to Apache or some such to replicate the RunWAR virtual directories, if you are deploying to a different container.

All that said, we can basically do anything we want, as we have full control over how things are done.  If errorPages was something _other_ than shorthand for the servlet spec of errorPages, I'd feel more comfortable making it all magical, but basically it's supposed to be something that's unverifiable, so verifying it is tricky.
    Like, we can definitely add a check, e.g. take `/404.cfm` and then see if `{webroot}/404.cfm` is a file that exists, but it could return a false negative, if for instance the location points at a URL that gets rewritten (`/genericErrorLocationAllMyAppsUse`).  So I don't know... maybe with the information I've provided you can think of something.  I'm open to ideas, just don't have any really nice solutions at the moment.

As for getting the originating URL for a 404, this should work:
`getPageContext().getRequest().getAttribute("javax.servlet.forward.request_uri")`

It might be non-trivial to add it to the request query string... hrm, or maybe not, come to think of it, if that parameter is only there for forwards... but we may then end up with people asking to turn it off, so I'd prefer to tell people to just get it from the request instead, as that will work with any servlet container (they'd just need to specify the errorPage in the web.xml vs. the command line).  For IIS it's a setting that can be turned off, so folks probably shouldn't rely on that anyway, FWIW.

**Comment by denuno** [comment]
Oh yeah, and as for the "white page of death" (heh) when you have a bad location for the error page, there's nothing else to really do, as like I said there's no pre-forwarding validation going on (trying to do so could cause lots of hard to track down problems), and you could end up with an infinite loop if it tried to do any more redirection after the first one-- which again, isn't checked for any kind of response.

We could probably do something to check the response, and have a nice error, but at "first thought" at least, it seems like it could be problematic.

**Comment by bdw429s** [comment]
@denuno If the error pages were designed to be a relative reference inside the web root, then I'm ok with it.   I thought at first perhaps it was only an oversight.   I'll just document the fact that it needs to be another valid web path inside the application.  Also also add a check to add the `/` to the start of any error page for the user since it sounds like there would never be a valid scenario that didn't have the leading slash.

To test the default, you just have to _only_ have the default error page configured and trigger a 404
To test the 500, you need to have an invalid 404 (like no leading slash) and then trigger a 404 and it then calls the 500 instead.

> As for getting the originating URL for a 404, this should work:
> `getPageContext().getRequest().getAttribute("javax.servlet.forward.request_uri")`

Close-- here are the attributes I'm seeing:
- **javax.servlet.error.status_code** = `404`
- **javax.servlet.error.request_uri** = `/nonexistant.html`
- **javax.servlet.error.message** = `Not Found`

And it looks like the query string is just passed through as usual to the `URL` scope.

**Comment by bdw429s** [comment]
>  and you could end up with an infinite loop if it tried to do any more redirection after the first one
Instead of trying to redirect, is it possible to just hardcode some sort of brief error message directly to the output stream?  Something that says there was an error displaying the error page and see if there's a `javax.servlet.error.message = Not Found` to include.
