### ISSUE TITLE
Listener Options

### ISSUE THREAD

**Issue by lmajano** [cfmlprojects/runwar#72]
@denuno What would be the best way to configure the listener options available in undertow: http://undertow.io/undertow-docs/undertow-docs-1.3.0/listeners.html

**Comment by denuno** [comment]
The only listener we didn't have was HTTP2, which I wanted to get in there, so the first implementation is in, along with a [LearningPushHandler](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/handlers/LearningPushHandler.java), which theoretically builds up a cache of things the server sends out over http and then can send it out over http2 if the browser supports it.  Seems pretty darn cool but I haven't tested it much.  Enabled by passing `-http2 true` or `--http2-enable true`.  HTTP2 basically requires SSL so that's automatically enabled if http2 is.
